# NOTE: frontend/nginx and certbot services run long sleep loops to maintain
# the LetsEncrypt certificates from certbot. The certificates expire every
# three months, so I figured a cert refresh every day would be more than
# sufficient.
services:
  frontend:
    profiles: ["frontend"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    # command snippet from https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
    command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./certbot/www/:/var/www/certbot # read challenge files from certbot
      - ./certbot/conf/:/etc/letsencrypt # read actual certs
      # TODO: nginx log volume?
      # TODO: configure this if I need to develop live on the Docker instance
      #   - /app/node_modules
      #   - ./frontend:/app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
  graphql-server:
    profiles: ["graphql-server"]
    build:
      context: ./graphql-server
      dockerfile: Dockerfile
    container_name: graphql-server
    restart: unless-stopped
    # ports:
    #   - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: raiseyourgame
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
      # TODO: switch availability based on env
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
  # LetsEncrypt certbot; certbot.eff.org
  certbot:
    # In this context, certbot can't configure nginx directly, so no point
    # running it as a service. Instead, while the frontend server is running,
    # run the certonly command to write the updated certificates:
    #
    # sudo docker compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ -d raiseyourga.me
    profiles: ["certbot"]
    image: certbot/certbot:latest
    # entrypoint snippet from https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 168h & wait $${!}; done;'"
    volumes:
      - ./certbot/www/:/var/www/certbot # write challenge files for nginx
      - ./certbot/conf/:/etc/letsencrypt # write actual certs

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  nginxdata:
    driver: local
